app: 
  name: machine_learning_info_bot
  log:
    directory: logs/machineLearningInfo.log
  telegram:
    url: https://api.telegram.org/bot
    chatId: PONER_AQUI_EL_CHAT_ID
    channel: PONER_AQUI_EL_CHANNEL_ID
    token: PONER_AQUI_EL_TOKEN_ID
    sessionId: PONER_AQUI_EL_SESSION_ID
    hash: PONER_AQUI_EL_HASH_ID
    summary: True